### ISSUE TITLE
NPM  Package Issue

### ISSUE THREAD

**Issue by jdziat** [nikku/easysax#10]
When using this as a dependency it is throwing an error that decode.js is unavailable. When i forked the current version and deployed to a private instance with all files included it resolved the issue. Noticed the issue when using the bpmn-js package.

**Comment by nikku** [comment]
Should be fixed via https://github.com/nikku/saxen/issues/9 already.

**Comment by jdziat** [comment]
Sorry, noticed it the day before making this ticket. Should of checked the closed issues. Thanks for the quick resolution.
